[global]

UIName = Objective Points
Description = Adds several mods' banners to the existing objective points.
DllName = WXPMod
Playable = 0
ModFolder = objective_points_SS_UA
ModVersion = 3.12
TextureFE = Art/UI/Textures/Title_winter_assault.tga

DataFolder.1 = Data

RequiredMod.1 = DXP2
RequiredMod.2 = W40K

-- Modified/Continued 2018-2019 by Kekoulis.
-- A continuation of jONES1979's original OP project.
-- All 3 point's models are embedded now in one model named \Art\EBPs\Environment\Gameplay\strategic_point_op.whm
-- Appropriate attribute RGDs files have been added to support the above model.^

-- If "your mod" has its own modification to these files ... 
-- ..\Data\attrib\ebps\environment\gameplay\relic_struct.rgd
-- ..\Data\attrib\ebps\environment\gameplay\strategic_objective_struct.rgd
-- ..\Data\attrib\ebps\environment\gameplay\strategic_point_flag.rgd
-- ...you should delete them if you want to have proper OP support for your mod. :P
-- For requests or reports,please visit the Revora thread of the current OP mod version:https://forums.revora.net/topic/111899-objective-points-mod-ver2582018uploaded-on-2882018/
-- Or contact me with a PM either on Revora,or Modb.I am also available on Discord.

--  Fully supported mods in this version:

-- Adeptus Mechanicus Explorators             
-- Black Templars 
-- Orks of Armageddon          
-- Chaos Renegades  
-- Craftworld Eldar  
-- Chaos Daemons             
-- Dark Angels	       
-- Emperor's Children
-- Harlequins          
-- Imperial Fists 
-- Ultramarines
-- Wolf Lords/Space Wolves
-- Night Lords
-- Farsight Enclaves
-- Word Bearers(RAGE mod)
-- Iron Warriors (Black Crusade Mod, Chapter 1)
-- World Eaters
-- Legion of the Damned
-- Deathwatch/Alien Hunters
-- 13th Company
-- Vostroyan Firstborn
-- Praetorians
-- Tyrannid Swarm
-- White Scars
-- Legion Titanicus
-- Legio Custodes
-- Updated default banner for any remaining unsupported race/mod.



--  Prev. version:

-- author: Promythyus, based on objective_points for Dark Crusade by Compiler. 
-- contact: Promythyus: brooksaar@gmail.com Compiler:spacedragons@free.fr
--
-- Original Author for the SS version: jONES1979
--
-- Banners included in this Version:
-- Relic Races : Chaos, Eldar, Imperial Guard, Necrons, Orks, Space Marines, Tau, Sisters of Battle, Dark Eldar
--
-- Banners for Mods:
-- Blood Angels
-- Inquisition: Daemonhunt
-- Steel Legion
-- Tyranids
-- Witch Hunters: Adepta Sororitas 
-- Deathwing                        
-- Dark Angels
-- Armoured Company
-- Thousand Sons
-- 
-- Banner for races not included Above:
-- Default banner