[global]
UIName = TheFinalExpansion
Description =
Playable = 1
DllName = WXPMod
ModFolder = TFE
ModVersion = 0.0.1.1684
ModGitParentCommit = fc61ff3e
TextureFE =
TextureIcon = 

DataFolder.1 = %LOCALE%\Data
DataFolder.2 = Data
DataFolder.3 = Data_Shared_Textures\%TEXTURE-LEVEL%
DataFolder.4 = Data_Sound\%SOUND-LEVEL%
DataFolder.5 = Data_Music
DataFolder.6 = Data_Whm\%MODEL-LEVEL%

RequiredMod.1 = DXP2
RequiredMod.2 = W40k
RequiredMod.3 = TFEReduxMaps
