[global]
UIName = TheFinalExpansion
Description = 
Playable = 1
DllName = WXPMod
ModFolder = TFE
ModVersion = 0.0.1.
1607

1607

1607

1607

1607

1607

1607

1606

1606

1606

1606

1606

1606

1606

1606

1606

1606

1606

1605





ModGitCommit = 92da98dee6ec81eb48abd1b18f191c145c6862f2























TextureFE = 
TextureIcon = 

DataFolder.1 = %LOCALE%\Data
DataFolder.2 = Data
DataFolder.3 = Data_Shared_Textures\%TEXTURE-LEVEL%
DataFolder.4 = Data_Sound\%SOUND-LEVEL%
DataFolder.5 = Data_Music
DataFolder.6 = Data_Whm\%MODEL-LEVEL%

RequiredMod.1 = DXP2
RequiredMod.2 = W40k
RequiredMod.3 = TFEReduxMaps